baseurl = "http://iwabm.github.io/"
languageCode = "en-us"
title = "Masaki Iwabuchi | 岩渕 正樹"
disqusShortname = "iwabm"

[params]
  description = "There is no time like the present."
  pagetitle = "iwabm on github"
  contentstitle = "Masaki Iwabuchi.web"
  author = "Masaki Iwabuchi"

[[params.social]]
  icon = "twitter"
  url = "https://twitter.com/powergradation"

[[params.social]]
  icon = "facebook"
  url = "https://www.facebook.com/masaki.iwabuchi"  

[[params.social]]
  icon = "instagram"
  url = "https://instagram.com/iwabm"  

[[params.social]]
    icon = "github"
    url = "https://github.com/iwabm"

[[params.social]]
    icon = "linkedin"
    url = "https://jp.linkedin.com/pub/masaki-iwabuchi/26/6b4/716"

[[params.social]]
    icon = "envelope-o"
    url = "mailto:ituki1059@gmail.com"